services:
  frontend:
    container_name: amc_cms_node
    build: frontend
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - ../frontend:/usr/src/app
    networks:
      - app-net

networks:
  app-net:
    external: true
